name: list-versions
on:
  workflow_dispatch:
    inputs: {}
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "PATH=$PWD/.akoi/bin:$PATH" >> $GITHUB_ENV
      - name: Install akoi
        uses: suzuki-shunsuke/akoi-installer@v0.1.0
      - run: akoi install
      - run: aws rds describe-db-engine-versions --region us-east-1 --engine aurora-postgresql | jq -r ".DBEngineVersions[].EngineVersion" > versions.txt
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - run: bash update.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
