name: list-versions
on:
  workflow_dispatch:
    inputs: {}
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - run: echo "PATH=$PWD/.akoi/bin:$PATH" >> $GITHUB_ENV
      - name: Install akoi
        uses: suzuki-shunsuke/akoi-installer@v0.1.0
      - run: akoi install

      - run: aws rds describe-db-engine-versions --region us-east-1 --engine aurora-postgresql | jq -r ".DBEngineVersions[].EngineVersion" | uniq > versions.txt
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - uses: suzuki-shunsuke/github-actions-renovate-github-tags-data-source@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
