name: list-versions
on:
  workflow_dispatch:
    inputs: {}
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: echo "PATH=$PWD/.akoi/bin:$PATH" >> $GITHUB_ENV
      - name: Install akoi
        uses: suzuki-shunsuke/akoi-installer@v0.1.0
      - run: akoi install

      - uses: suzuki-shunsuke/github-actions-aws-rds-available-engine-versions@main
        with:
          engine: aurora-postgresql
          github_token: ${{ secrets.GITHUB_TOKEN }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
